const fs = require("node:fs");
let types = fs.readFileSync("src/types/index.ts", "utf8");
types = types.replace(/createdAt\?:\s*string;/g, "createdAt?: Date;");
types = types.replace(/createdAt:\s*string;/g, "createdAt: Date;");
types = types.replace(/updatedAt\?:\s*string;/g, "updatedAt?: Date;");
types = types.replace(/updatedAt:\s*string;/g, "updatedAt: Date;");
types = types.replace(/startedAt:\s*string;/g, "startedAt: Date;");
types = types.replace(/startedAt\?:\s*string;/g, "startedAt?: Date;");
types = types.replace(/submittedAt:\s*string;/g, "submittedAt: Date;");
types = types.replace(/submittedAt\?:\s*string;/g, "submittedAt?: Date;");
types = types.replace(/examDate:\s*string;/g, "examDate: Date;");
fs.writeFileSync("src/types/index.ts", types);
